version: 2

jobs:
  test-core:
    working_directory: ~/repo/packages/core
    docker:
      - image: circleci/node:lts
    steps:
      - checkout:
          path: ~/repo
      - run: yarn
      - run: yarn coverage

  test-multer:
    working_directory: ~/repo/packages/multer
    docker:
      - image: circleci/node:lts
    steps:
      - checkout:
          path: ~/repo
      - run: yarn
      - run: yarn coverage

workflows:
  version: 2
  core:
    jobs:
      - test-core
  multer:
    jobs:
      - test-multer
