version: 2

defaults: &defaults
  docker:
    - image: circleci/node:lts

jobs:
  test-core:
    <<: *defaults
    working_directory: ~/repo/packages/core
    steps:
      - checkout:
          path: ~/repo
      - run: yarn
      - run: yarn coverage
      - run: ./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov
      - persist_to_workspace:
          root: ~/repo
          paths:
            - packages/core/coverage.lcov

  test-multer:
    <<: *defaults
    working_directory: ~/repo/packages/multer
    steps:
      - checkout:
          path: ~/repo
      - run: yarn
      - run: yarn coverage
      - run: ./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov
      - persist_to_workspace:
          root: ~/repo
          paths:
            - packages/multer/coverage.lcov

  coverage:
    <<: *defaults
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      - attach_workspace:
          at: ~/repo
      - run: cat packages/core/coverage.lcov > coverage.lcov
      - run: echo "<<<<<< EOF" >> coverage.lcov
      - run: cat packages/multer/coverage.lcov >> coverage.lcov
      - run: echo "<<<<<< EOF" >> coverage.lcov
      - run: bash <(curl -s https://codecov.io/bash) -Z -C $CIRCLE_SHA1

  deploy-core:
    <<: *defaults
    working_directory: ~/repo/packages/core
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

  deploy-multer:
    <<: *defaults
    working_directory: ~/repo/packages/multer
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  test-deploy:
    jobs:
      - test-core
      - test-multer
      - coverage:
          requires:
            - test-core
            - test-multer
      - deploy-core:
          requires:
            - test-core
          filters:
            tags:
              only: /^core-v.*/
            branches:
              only: /master/
      - deploy-multer:
          requires:
            - test-multer
          filters:
            tags:
              only: /^multer-v.*/
            branches:
              only: /master/
