version: 2

defaults: &defaults
  docker:
    - image: circleci/node:lts

jobs:
  test-core:
    <<: *defaults
    working_directory: ~/repo/packages/core
    steps:
      - checkout:
          path: ~/repo
      - run: yarn
      - run: yarn coverage
      - run: ./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov
      - run: ./node_modules/.bin/codecov -F core

  test-multer:
    <<: *defaults
    working_directory: ~/repo/packages/multer
    steps:
      - checkout:
          path: ~/repo
      - run: yarn
      - run: yarn coverage
      - run: ./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov
      - run: ./node_modules/.bin/codecov -F multer

  deploy-core:
    <<: *defaults
    working_directory: ~/repo/packages/core
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

  deploy-multer:
    <<: *defaults
    working_directory: ~/repo/packages/multer
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  core:
    jobs:
      - test-core
      - deploy-core:
          requires:
            - test-core
          filters:
            tags:
              only: /^core-v.*/
            branches:
              only: /master/
  multer:
    jobs:
      - test-multer
      - deploy-multer:
          requires:
            - test-multer
          filters:
            tags:
              only: /^multer-v.*/
            branches:
              only: /master/
